# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Lanyon
tagline:             'Brain Flow'
description:         'A drawer separating different thoughts, ideas, and projects I've been working on. Click <a href="bjchia.github.io" target="_blank">here</a> to go back to main page.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            `
paginate_path: blog/page:num

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
