# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               Brain Flow
tagline:             'The talking of soul with itself'
description:         'A container separating different thoughts, ideas, and projects I've been working on. Click <a href="bjchia.github.io" target="_blank">here</a> to go back to main page.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            1
paginate_path: blog/page:num

# About/contact
author:
  name:              Benjamin Chia
  url:               https://bjchia.github.io
  email:             bjchia@ucdavis.edu

# Custom vars
version:             1.0.0
